In [1]:
import numpy as np

In [23]:
class Cube:
    def __init__(self, height, width, depth, shape):
        self.height = height
        self.width = width
        self.depth = depth
        self.shape = shape
        
    def mount_matrix(self, type_):
        arr = list(self.shape)
        if type_ == 'number':
            arr = [i for i in range(0,self.height*self.width*self.depth)]
            
        nn = []
        height = pit_height
        width = pit_width
        depth=pit_depth
        first = 0
        last = height*width
        for i in range(1,depth+1):
            nn.append(arr[first:last])
            first = last
            last = height*width*(i+1)

        n = []
        first = 0
        last = width
        for i in range(0,height):
            m=[]
            for j in range(0,depth):
                m.append(nn[j][first:last])
            n.append(list(np.array(m).flatten()))
            first = last
            last = first+width
        return n
    
    def get_min_max_height(self, char_shape):
        min_height = 0
        max_height = 0
        for i in range(1,len(char_shape)):
            indxs_ant = [i for i,x in enumerate(char_shape[i-1][0]) if x == '.']
            indxs_curr = [i for i,x in enumerate(char_shape[i][0]) if x == '.']
#             print(indxs_ant,indxs_curr)
            common_list = set(indxs_ant).intersection(indxs_curr)
            if len(common_list) == 0:
                min_height = i+1

            if len(common_list) > len(char_shape[0][0])/2:
                max_height=i-1
                break
#             print(i,common_list,len(p_shape[0][0])/2)

        return min_height, max_height

    def get_prohibted_indexes(self, obj):
        ind = set()
        for index, elem in enumerate(self.shape):
            if elem == obj:
                ind.add(index)
                if index > self.width * self.depth:
                    ind.add(index-self.width*self.depth)
        return ind
    
    
    def get_all_possibilities(self,n,pi,prohibited,height_index=0):
        layer = n[height_index]
        nnn = np.array(layer).reshape(self.depth,self.width)
        possibilities = []
        for ind,p in enumerate(pi):
    #         print("p",p)

            entry_shape = np.array(list(p[3]))
            entry_shape = entry_shape.reshape(p[2]*p[1],p[0])
    #         print(new_width)
            if p[1] >= 1:
                if p[1] <= self.width:
                    for i in range(self.depth-(p[1]-1)):
                        first = 0
                        last = self.width
    #                     print("i",i,nnn[i])
                        for j in range(self.width-(p[0]-1)):
                            el = nnn[i][first+j:p[0]+first+j]
    #                         print("j",el,entry_shape[0])

                            ell = [x for ind,x in enumerate(el) if entry_shape[0][ind] == '#']
    #                         print("j",el,entry_shape[0])
                            if any(x in prohibited for x in ell):
                                pass
                            else:
                                possibilities.append((el,p[4],j,i))
                        first=last
                        last = self.width+first
            if p[1] > 1:
                if p[1] <= self.depth:
                    nnn = np.rot90(nnn)
                    for i in range(self.depth-(p[0]-1)):
                        first = 0
                        last = self.width
    #                     print("ii",i,nnn[i])
                        for j in range(self.width-(p[1]-1)):
                            el = nnn[i][first+j:p[1]+first+j]
                            # print(el,first+j,p[1]+first+j)
                            if any(x in prohibited for x in el):
                                pass
                            else:
                                possibilities.append((el,p[4],j,i))
                        first=last
                        last = self.width+first

        return possibilities

    def check_bad_good_possibility(self,x,entry,entry_shape,arr_shape,height_index):
        for i in range(entry[2]):
            for j in range(entry[0]):
    #             print(i+height_index,j+x)
                if self.depth > 1:
                    return True
                else:
                    if arr_shape[i+height_index][j+x] != '#':
                        arr_shape[i+height_index][j+x] = entry_shape[i][j]
                    elif arr_shape[i+height_index][j+x] == '#' and entry_shape[i][j] == '#':
    #                     print("aqui1")
                        return False
                    if i+height_index > height_index:
                        if entry_shape[i][j] == '#':
                            if arr_shape[i+height_index-1][j+x] == '.':
    #                             print("aqui2")
                                return False

        return True
    
    def get_improved_possibilities(self,possibilities):
        good_possibilities = []
        bad_possibilities = []
        for p in possibilities:
    #         p = possibilities[1]
            arr_shape=np.array(self.mount_matrix('char'))
        
            a, pind, x, z = p
    #         print(p)
            entry = [x for x in pi if int(x[4]) == pind][0]
            entry_shape = np.array(list(entry[3]))
            entry_shape = entry_shape.reshape(entry[2]*entry[1],entry[0])
            good = self.check_bad_good_possibility(x,entry, entry_shape,arr_shape,height_index)
            if good:
                good_possibilities.append((a, pind, x, z))
            else:
                bad_possibilities.append((a, pind, x, z))
        return good_possibilities, bad_possibilities

In [24]:
pit_shape = '###.....................................................................'

pi = [(3, 1, 1, '###', 0), (1, 1, 3, '###', 1), (1, 3, 1, '###', 2)]

pit_width=3
pit_height=8
pit_depth=3

cube = Cube(pit_height,pit_width,pit_depth,pit_shape)


In [25]:
n=cube.mount_matrix('number')
n

[[0, 1, 2, 24, 25, 26, 48, 49, 50],
 [3, 4, 5, 27, 28, 29, 51, 52, 53],
 [6, 7, 8, 30, 31, 32, 54, 55, 56],
 [9, 10, 11, 33, 34, 35, 57, 58, 59],
 [12, 13, 14, 36, 37, 38, 60, 61, 62],
 [15, 16, 17, 39, 40, 41, 63, 64, 65],
 [18, 19, 20, 42, 43, 44, 66, 67, 68],
 [21, 22, 23, 45, 46, 47, 69, 70, 71]]

In [26]:

p_shape=cube.mount_matrix('char')
p_shape


[['#', '#', '#', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '.', '.']]

In [27]:
min_height,max_height=cube.get_min_max_height(p_shape)

In [28]:
min_height,max_height

(2, 1)

In [29]:
prohibited = cube.get_prohibted_indexes("#")

In [30]:
height_index = 0
possibilities = cube.get_all_possibilities(n,pi,prohibited,height_index)


In [31]:
possibilities

[(array([24, 25, 26]), 0, 0, 1),
 (array([48, 49, 50]), 0, 0, 2),
 (array([24]), 1, 0, 1),
 (array([25]), 1, 1, 1),
 (array([26]), 1, 2, 1),
 (array([48]), 1, 0, 2),
 (array([49]), 1, 1, 2),
 (array([50]), 1, 2, 2)]

In [32]:

_, pind, x, z = possibilities[1]

print(pind,x,z)

entry = pi[pind]
print(entry)
entry_shape = np.array(list(entry[3]))
entry_shape = entry_shape.reshape(entry[2],entry[0])
print(entry_shape)

new_width = np.count_nonzero(entry_shape[0] == '#')
print(new_width)


0 0 2
(3, 1, 1, '###', 0)
[['#' '#' '#']]
3


In [34]:
good_possibilities, bad_possibilities = cube.get_improved_possibilities(possibilities)

# print(arr_shape)

print(good_possibilities)

[(array([24, 25, 26]), 0, 0, 1), (array([48, 49, 50]), 0, 0, 2), (array([24]), 1, 0, 1), (array([25]), 1, 1, 1), (array([26]), 1, 2, 1), (array([48]), 1, 0, 2), (array([49]), 1, 1, 2), (array([50]), 1, 2, 2)]


In [35]:
print(bad_possibilities)

[]


In [36]:
possibilities

[(array([24, 25, 26]), 0, 0, 1),
 (array([48, 49, 50]), 0, 0, 2),
 (array([24]), 1, 0, 1),
 (array([25]), 1, 1, 1),
 (array([26]), 1, 2, 1),
 (array([48]), 1, 0, 2),
 (array([49]), 1, 1, 2),
 (array([50]), 1, 2, 2)]